### ISSUE TITLE
Fluids do not render properly

### ISSUE THREAD

**Issue by Yulife** [0tho/CustomItems#16]
![2015-01-01_14 10 31](https://cloud.githubusercontent.com/assets/8559428/5592212/fd9944b0-91bf-11e4-931a-4d8627e2be62.png)
 Fluids that got added via CustomItems are not properly rendered in specific tanks.

Seared Tank (Tinkers' Construct): Renders as Water

Ender Tank (Ender Storage): Renders as Missing Texture

Heat Resistant Tank (Mariculture): Renders properly, surprisingly.

Tank (Buildcraft): Renders as Missing Texture

Tank (OpenBlocks): Renders as Missing Texture

Fluid Tanks (EnderIO): Doesn't even render, is invisible

Portable Tank(s) (Thermal Expansion): Renders as Lava

**Comment by 0tho** [comment]
I will look into it, should be fixed in the near future. Probably next version

**Comment by Yulife** [comment]
Just discovered that it doesn't show properly in NEI either.
[Smeltery](http://puu.sh/dVyjF/dbd546b103.png)
[Fluid Transposer](http://puu.sh/dVyk1/3818bcdce2.png)
Also you can see that the bucket doesn't render properly either in the Fluid Transposer.

**Comment by Atraxi** [comment]
I think all of these are the same cause - the Fluid icons aren't being set, with Fluid acting essentially as the Item form of BlockFluids (This causes the Fluid to search for textures in /items rather than /blocks, even though in practically every scenario you want them to be the same, the best option I found was to point it to the already registered BlockFluid textures).

I've just started a small mod of my own and fixed this a couple days ago, feel free to use mine as an example: https://github.com/Atraxi/PandemiCraft/blob/master/src/main/java/eviltalkingpie/pandemicraft/proxy/ClientProxy.java

**Comment by 0tho** [comment]
Thanks Atraxi. I dont think you have to use proxy for that. I have looked at [TC](https://github.com/SlimeKnights/TinkersConstruct/blob/d0894550633f5565dbc0cf14f78a7ae6bd57c2a7/src/main/java/tconstruct/blocks/slime/SlimeFluid.java) and its slime fluid block it sets the fluid IIcons.

I changed my code to do the "same", and now it works fine for the mods I tested
