### ISSUE TITLE
Can't Understand How To Make Armor Models Work

### ISSUE THREAD

**Issue by earthcrafterman** [0tho/CustomItems#33]
In trying to add a model to my armor I found it's showing only as a black box in place of the legs, I would appreciate it if someone were to assist me in making the textures properly function.

My Code for making the boots:
http://pastebin.com/CwrprfhC

My resourcepack containing the textures:
https://drive.google.com/file/d/0B8GPmOdcLf_fLU45ZDZ4MEVGa2c/view?usp=sharing

**Comment by Cyd007** [comment]
I want to say sorry for the delay to responding to this but I believe I found out whats wrong. If you look at line 5 of your configuration file, it seems that syntax for the texture is incorrect. See the following:

You have this:

"textureName":"boothide",

This is what it should be: 

"textureName": "boothide",

Yes just one little space between the : and "boothide"

Here is the pastebin link for the new config:
http://pastebin.com/M5BAfADJ

Otherwise everything else looks alright.
